title: OmniROM Blog
email: omniromorg@gmail.com
description: 'Omni is about innovation, new features, transparency, community, and freedom.'
baseurl: "/"
url: "https://blog.omnirom.org"
twitter_username: omni_rom
github_username:  omnirom
paginate: 5

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:  pretty
#relative_permalinks:	true

# Custom vars
#plugins:  [jekyll-paginate]
include: _redirects

plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
